import type { InputsProjet } from "./types";

/** Valeurs de départ neutres pour un premier rendu. */
export const INPUTS_INITIAUX: InputsProjet = {
  nomProjet: "Mon projet immobilier",
  typeBien: "ancien",
  prixAchat: 150_000,
  fraisAgence: 0,
  fraisRecherche: 0,
  anneeAcquisition: new Date().getFullYear(),
  detention: {
    mode: "sci_ir",
    regimeFiscal: "ir_foncier_reel",
  },
  financement: {
    montantEmprunt: 150_000,
    tauxNominal: 0.035,
    dureeAnnees: 20,
    assuranceMensuelleFixe: 25,
    fraisDossier: 1000,
    typeGarantie: "ippd",
    differeMois: 0,
  },
  biens: [
    { nombre: 1, loyerMensuel: 800, joursVacancePart: 15 },
    { nombre: 0, loyerMensuel: 0, joursVacancePart: 0 },
    { nombre: 0, loyerMensuel: 0, joursVacancePart: 0 },
    { nombre: 0, loyerMensuel: 0, joursVacancePart: 0 },
  ],
  charges: {
    taxeFonciereAnnuelle: 1500,
    tomAnnuelle: 150,
    coproprieteAnnuelle: 800,
    fraisGestionPctLoyers: 0,
    etatDesLieux: 0,
    gliPctLoyers: 0,
    pnoAnnuelle: 200,
    autresAnnuelle: 0,
    fraisComptablesIR: 0,
    fraisComptablesIS: 600,
    traitementFraisAcquisition: "amortissement10",
    crl25pct: false,
  },
  travaux: Array.from({ length: 10 }, (_, i) => ({
    annee: i + 1,
    deductibleParticuliers: i === 0 ? 5000 : 0,
    deductibleSocietes: 0,
    augmentationLoyerAnnuelle: 0,
  })),
  amortComposants: [
    { nom: "Terrain", proportion: 0.2, dureeAnnees: 0 },
    { nom: "Gros œuvre", proportion: 0.4, dureeAnnees: 40 },
    { nom: "Toiture", proportion: 0.2, dureeAnnees: 30 },
    { nom: "Électricité", proportion: 0.1, dureeAnnees: 20 },
    { nom: "Aménagement intérieur", proportion: 0.1, dureeAnnees: 10 },
  ],
  associes: [
    {
      prenom: "Associé 1",
      apportCapital: 1000,
      apportCompteCourant: 0,
      pctParts: 1.0,
      revenuNetImposableHorsFoncier: 35_000,
      deficitsFonciersPrealables: 0,
      nbPartsFiscales: 1,
      nbPartsEnfants: 0,
    },
  ],
  revente: {
    choix: "inflation",
    anneeRevente: 10,
    inflationAnnuelle: 0.02,
    rendementCibleAcheteur: 0.06,
    prixFixe: 0,
    fraisRevente: 0.015,
  },
  irlAnnuel: 0.015,
  inflationCharges: 0.02,
  horizonAnnees: 10,
};
